### ISSUE TITLE
Handling invalid parameters

### ISSUE THREAD

**Issue by mpaddle** [PaddleHQ/python-aws-ssm#8]
When a parameter is requested through `get_parameters` that does not exist, we are currently ignoring the `InvalidParameters` key in the boto3 response which would tell us of our mistake.

For instance:

```
parameter_store = ParameterStore(ssm_client)
parameters = parameter_store.get_parameters(["/no/nope/noooo"])
assert len(parameters) == 0
```

Should we raise an error in this case? AWS tells us in the response, with the `InvalidParameters` key, that this request cannot be fulfilled so that seems helpful to me.

Regarding `get_parameters_by_path`, how do people check if required parameters are present? Should we maybe add an optional parameter to check for required parameters?

**Comment by mpaddle** [comment]
For the first case, I suggest we raise a new error called `InvalidParametersError` with a list of parameters that are supposedly invalid. Maybe with a message reminding the caller to check their AWS configuration and SSM keys?

**Comment by mpaddle** [comment]
For the second case, I suggest we change the signature to

```
    def get_parameters_by_path(
        self,
        ssm_base_path: str,
        with_decryption: bool = True,
        recursive: bool = False,
        nested: bool = False,
        parameters: Optional[Set[str]] = None
    ) -> Dict[str, Union[Dict, Optional[str]]]:
```

If the new parameter `parameters` is None, the behavior of the method remains the same. If it's a set of key names, we ensure that those keys are included in the map of parameters. I'm not sure about which exception to raise though: `InvalidParametersError` (from the first case) is particular to AWS so maybe we shouldn't overload it.

**Comment by vhemt** [comment]
Solved: https://github.com/PaddleHQ/python-aws-ssm/pull/10
